# gem 'mysql2', '~> 0.4.2'
  development:
    adapter: mysql2
    encoding: utf8
    database: all_app
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    secure_auth: false


  test:
    adapter: mysql2
    encoding: utf8
    database: all_app_test
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    secure_auth: false

  production:
    adapter: mysql2
    encoding: utf8
    database: all_app
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    secure_auth: false